#INCLUDE <P16F628A.INC>		;ARQUIVO PADR�O MICROCHIP PARA 16F628A
RADIX DEC
__CONFIG H'3F10'

	CBLOCK	0x20	;ENDERE�O INICIAL DA MEM�RIA DE USU�RIO
	CONTADOR1	
    CONTADOR2
    CONTADOR3
    AUX
	ATUAL
	ENDC			;FIM DO BLOCO DE MEM�RIA		

#DEFINE	BOTAO	PORTA,2	;PORTA DO BOT�O
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

#DEFINE	LED	PORTB,0	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO
	ORG	0x00		;ENDERE�O INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SA�DAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SA�DA
	CLRF	INTCON		;TODAS AS INTERRUP��ES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON		;DEFINE O MODO DO COMPARADOR ANAL�GICO

MAIN
	MOVLW	0
	MOVWF	AUX    ; AUX = 0 SE BOTAO NAO FOR PRE

	CALL ZERO      ;DISPLAY 0
    CALL  ATRASO 
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  ZEROD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 0    		 

	CALL  UM        ;DISPLAY 1
    CALL  ATRASO 
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  UMD    ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 1    

	CALL DOIS      ;DISPLAY 2
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  DOISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 2 

	CALL TRES      ;DISPLAY 3
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  TRESD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 3 

	CALL QUATRO    ;DISPLAY 4
    CALL ATRASO
    BTFSC AUX, 0  ; TESTAR SE AUX EH ZERO OU UM
    GOTO  QUATROD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                  ; COMECAR DESCIDA DO 4 


	CALL CINCO     ;DISPLAY 5
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  CINCOD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 5 

	CALL SEIS      ;DISPLAY 6
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SEISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 6 

	CALL SETE      ;DISPLAY 7
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SETED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 7 

    CALL OITO      ;DISPLAY 8
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  OITOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 8 

	CALL NOVE      ;DISPLAY 9
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  NOVED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 9 

	CALL OITO      ;DISPLAY 8
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  OITOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 8 

	CALL SETE      ;DISPLAY 7
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SETED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 7 

	CALL SEIS      ;DISPLAY 6
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SEISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 6 

	CALL CINCO     ;DISPLAY 5
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  CINCOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 5 

	CALL QUATRO    ;DISPLAY 4
    CALL ATRASO
    BTFSC AUX, 0  ; TESTAR SE AUX EH ZERO OU UM
    GOTO  QUATROD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                  ; COMECAR DESCIDA DO 4 

	CALL TRES      ;DISPLAY 3
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  TRESD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 3 

	CALL DOIS      ;DISPLAY 2
    CALL ATRASO
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  DOISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 2 

	CALL UM        ;DISPLAY 1
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  UMD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 1 

    CALL ATRASO
    GOTO MAIN 
NOVED
    CALL NOVE
    CALL ATRASOM
OITOD
    CALL OITO
    CALL ATRASOM
SETED
    CALL SETE
    CALL ATRASOM
SEISD
    CALL SEIS
    CALL ATRASOM
CINCOD
    CALL CINCO
    CALL ATRASOM
QUATROD
    CALL QUATRO
    CALL ATRASOM
TRESD
    CALL TRES
    CALL ATRASOM
DOISD
    CALL DOIS
    CALL ATRASOM
UMD
    CALL UM
    CALL ATRASOM
ZEROD
    CALL ZERO
    CALL ATRASOM
    GOTO MAIN


; FUNCAO PARA DESCER ELEVADOR CASO O BOTAO FOR PRECIONADO
; INTERROMPE LACOS DE ATRASO	
APERTOU
	MOVLW	1
	MOVWF	CONTADOR1	; contador1=0
	MOVLW	1
	MOVWF	CONTADOR2	; contador2=0
	MOVLW	1
	MOVWF	CONTADOR3	; contador3=0
	MOVLW	1
	MOVWF	AUX  	    ; AUX=1 para indicar que botao foi pressionado
	RETURN

;;;;;;;;;;;;;  FUNCOES DE ATRASO ;;;;;;;;;;;;;
ATRASO				
	MOVLW	105
	MOVWF	CONTADOR1	; contador1=255
    
ATRASO1		
	MOVLW	99
	MOVWF	CONTADOR2	; contador2=40
	NOP
	ATRASO2		
		MOVLW	35
		MOVWF	CONTADOR3	; contador1=129
        BTFSC	BOTAO		;O BOT�O EST� PRESSIONADO?
        GOTO    ATRASO3     ;NAO -> CONTINUAR O LOOP
	    CALL	APERTOU 	;SIM -> IR FUNCAO DE INCENDIO
		ATRASO3	
            NOP	
			NOP
		    DECFSZ	CONTADOR3	; contador3--
			GOTO	ATRASO3     ; se nao for zero continuar loop
	    DECFSZ	CONTADOR2	; contador2--
		GOTO	ATRASO2	; se nao for zero continuar loop
	
    DECFSZ	CONTADOR1	; contador2--
	GOTO	ATRASO1	 ; se nao for zero continuar loop
	RETURN	 ;ir para funcao atraso auxiliar

ATRASOM				
	MOVLW	105
	MOVWF	CONTADOR1	; contador1=255
    
ATRASO1M		
	MOVLW	99
	MOVWF	CONTADOR2	; contador2=40
	NOP
	ATRASO2M		
		MOVLW	35
		MOVWF	CONTADOR3	; contador1=129
		ATRASO3M	
            NOP	
		    DECFSZ	CONTADOR3	; contador3--
			GOTO	ATRASO3M     ; se nao for zero continuar loop
	    DECFSZ	CONTADOR2	; contador2--
		GOTO	ATRASO2M	; se nao for zero continuar loop
	
    DECFSZ	CONTADOR1	; contador2--
	GOTO	ATRASO1M	 ; se nao for zero continuar loop
	RETURN	 ;ir para funcao atraso auxiliar

;;;;;;;;;; FUNCOES PARA CONTROLAR DISPLAY ;;;;;;;;;;


;APAGAR LEDS
BOTAO_LIB
    BCF	    PORTB, 0   	;N�O, ACENDE O LED
	BCF	    PORTB, 1   	;N�O, ACENDE O LED
    BCF	    PORTB, 2  	;N�O, ACENDE O LED
    BCF	    PORTB, 3  	;N�O, ACENDE O LED
    BCF	    PORTB, 5  	;N�O, ACENDE O LED
    BCF	    PORTB, 6  	;N�O, ACENDE O LED
    BCF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 0
ZERO 	
    MOVLW	0
	MOVWF	ATUAL	; ATUAL = 0
    BCF     PORTB, 0 ; APAGA O LED
    BSF	    PORTB, 1 ; ACENDE O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BSF	    PORTB, 7 ; ACENDE O LED
	RETURN


;FUNCAO PARA ACENDER DISPLAY NO ANDAR 1
UM 	
    MOVLW	1
	MOVWF	ATUAL	; ATUAL = 1
    BCF     PORTB, 0 ; APAGA O LED
    BCF     PORTB, 1 ; APAGA O LED
    BCF     PORTB, 2 ; APAGA O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 2
DOIS
    MOVLW	2
	MOVWF	ATUAL	; ATUAL = 2
    BSF	    PORTB, 0   	; ACENDE O LED
    BCF     PORTB, 1    ; APAGA O LED
	BSF	    PORTB, 2   	; ACENDE O LED 
    BSF	    PORTB, 3   	; ACENDE O LED
    BCF     PORTB, 5    ; APAGA O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 3
TRES
    MOVLW	3
	MOVWF	ATUAL	; ATUAL = 3
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0 ; ACENDE O LED
    BCF     PORTB, 1 ; APAGA O LED
	BSF	    PORTB, 2 ; ACENDE O LED 
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 4
QUATRO
    MOVLW	4
	MOVWF	ATUAL	; ATUAL = 4
    BSF	    PORTB, 0 ; ACENDE O LED
	BSF	    PORTB, 1 ; ACENDE O LED
    BCF     PORTB, 2 ; APAGA O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 5
CINCO
    MOVLW	5
	MOVWF	ATUAL	; ATUAL = 5
    BSF	    PORTB, 0 ; ACENDE O LED
	BSF	    PORTB, 1 ; ACENDE O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BCF     PORTB, 3 ; APAGA O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 6
SEIS
    MOVLW	6
	MOVWF	ATUAL	; ATUAL = 6
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BCF     PORTB, 3 ; APAGA O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 7
SETE
    MOVLW	7
	MOVWF	ATUAL	; ATUAL = 7
    BCF     PORTB, 0 ; APAGA O LED
    BCF     PORTB, 1 ; APAGA O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 8
OITO
    MOVLW	8
	MOVWF	ATUAL	; ATUAL = 8
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 9
NOVE
    MOVLW	9
	MOVWF	ATUAL	; ATUAL = 9
	BSF	    PORTB, 0   	; ACENDE O LED
    BSF	    PORTB, 1  	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN


	END			;OBRIGAT�RIO


