#INCLUDE <P16F628A.INC>		;ARQUIVO PADRAO MICROCHIP PARA 16F628A
RADIX DEC
__CONFIG H'3F10'

	CBLOCK	0x20	;ENDERECO INICIAL DA MEMORIA DE USUARIO
	CONTADOR1	
    CONTADOR2
    CONTADOR3
	CONTADOR4
	CONTADOR5
    AUX
	ENDC			;FIM DO BLOCO DE MEMORIA		

#DEFINE	BOTAO	PORTA,2	;PORTA DO BOTAO
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

#DEFINE	LED	PORTB,0	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO
	ORG	0x00		;ENDERECO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAIDAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SAIDA
	CLRF	INTCON		;TODAS AS INTERRUPCOES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON		;DEFINE O MODO DO COMPARADOR ANALOGICO

MAIN
	MOVLW	0
	MOVWF	AUX    ; AUX = 0 SE BOTAO NAO FOR PRE

	CALL ZERO      ;DISPLAY 0
    CALL  DEMORA_2S 
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  ZEROD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 0    		 

	CALL  UM        ;DISPLAY 1
    CALL  DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  UMD    ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 1    

	CALL DOIS      ;DISPLAY 2
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  DOISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 2 

	CALL TRES      ;DISPLAY 3
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  TRESD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 3 

	CALL QUATRO    ;DISPLAY 4
    CALL DEMORA_2S
    BTFSC AUX, 0  ; TESTAR SE AUX EH ZERO OU UM
    GOTO  QUATROD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                  ; COMECAR DESCIDA DO 4 


	CALL CINCO     ;DISPLAY 5
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  CINCOD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 5 

	CALL SEIS      ;DISPLAY 6
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SEISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 6 

	CALL SETE      ;DISPLAY 7
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SETED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 7 

    CALL OITO      ;DISPLAY 8
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  OITOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 8 

	CALL NOVE      ;DISPLAY 9
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  NOVED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 9 

	CALL OITO      ;DISPLAY 8
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  OITOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 8 

	CALL SETE      ;DISPLAY 7
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SETED  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 7 

	CALL SEIS      ;DISPLAY 6
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  SEISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 6 

	CALL CINCO     ;DISPLAY 5
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  CINCOD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 5 

	CALL QUATRO    ;DISPLAY 4
    CALL DEMORA_2S
    BTFSC AUX, 0  ; TESTAR SE AUX EH ZERO OU UM
    GOTO  QUATROD ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                  ; COMECAR DESCIDA DO 4 

	CALL TRES      ;DISPLAY 3
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  TRESD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 3 

	CALL DOIS      ;DISPLAY 2
    CALL DEMORA_2S
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  DOISD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 2 

	CALL UM        ;DISPLAY 1
    BTFSC AUX, 0 ; TESTAR SE AUX EH ZERO OU UM
    GOTO  UMD  ; SE NAO FOR ZERO -> BOTAO PRESSIONADO
                 ; COMECAR DESCIDA DO 1 

    CALL DEMORA_2S
    GOTO MAIN 

NOVED
    CALL NOVE
    CALL DEMORA_1S
OITOD
    CALL OITO
    CALL DEMORA_1S
SETED
    CALL SETE
    CALL DEMORA_1S
SEISD
    CALL SEIS
    CALL DEMORA_1S
CINCOD
    CALL CINCO
    CALL DEMORA_1S
QUATROD
    CALL QUATRO
    CALL DEMORA_1S
TRESD
    CALL TRES
    CALL DEMORA_1S
DOISD
    CALL DOIS
    CALL DEMORA_1S
UMD
    CALL UM
    CALL DEMORA_1S
ZEROD
    CALL ZERO
    CALL DEMORA_1S
    GOTO MAIN


; FUNCAO PARA DESCER ELEVADOR CASO O BOTAO FOR PRESSIONADO
; INTERROMPE LACOS DE ATRASO	
APERTOU
	MOVLW	1
	MOVWF	CONTADOR1	; contador1=0
	MOVWF	CONTADOR2	; contador2=0
	MOVWF	CONTADOR3	; contador3=0
	MOVWF	AUX  	    ; AUX=1 para indicar que botao foi pressionado
	RETURN

;;;;;;;;;;;;;  FUNCOES DE ATRASO ;;;;;;;;;;;;;
DEMORA_2S				
	MOVLW	90
	MOVWF	CONTADOR1	; 
    
	LOOP1_2S		
        BTFSS	BOTAO		;O BOTAO ESTA PRESSIONADO?
	    CALL	APERTOU 	;SIM -> IR FUNCAO DE INCENDIO
		BTFSS	AUX, 0
		CALL    DEMORA_20MS ;DEMORAR ENTRE 20 E 50 MS	
		DECFSZ	CONTADOR1	; CONTADOR1--
		GOTO	LOOP1_2S	 ; se nao for zero continuar loop
	RETURN	; FIM DEMORA_2S

DEMORA_1S				
	MOVLW	13
	MOVWF	CONTADOR1	; COLOCA VALOR CONTADOR
    
	LOOP1_1S	
		MOVLW	76
		MOVWF	CONTADOR2	; COLOCA VALOR CONTADOR
		LOOP2_1S
			MOVLW	250
			MOVWF	CONTADOR3	; COLOCA VALOR CONTADOR
			LOOP3_1S
				NOP		
		    	DECFSZ	CONTADOR3	; contador3--
				GOTO	LOOP3_1S     ; se nao for zero continuar loop
	    	DECFSZ	CONTADOR2	; contador2--
			GOTO	LOOP2_1S	; se nao for zero continuar loop
		DECFSZ	CONTADOR1	; contador2--
		GOTO	LOOP1_1S	 ; se nao for zero continuar loop

	MOVLW	12
	MOVWF	CONTADOR4	; COLOCA VALOR NO CONTADOR

	LOOP4_1S
		MOVLW 	244
		MOVWF	CONTADOR5	; COLOCA VALOR NO CONTADOR
		LOOP5_1S
			DECFSZ	CONTADOR5	; CONTADOR5--
			GOTO LOOP5_1S
		DECFSZ	CONTADOR4	; CONTADOR4--
		GOTO LOOP4_1S
	RETURN	 ;ir para funcao atraso auxiliar

DEMORA_20MS
	MOVLW	29
	MOVWF	CONTADOR4	; COLOCA VALOR NO CONTADOR

	LOOP1_20MS
		MOVLW 	254
		MOVWF	CONTADOR5	; COLOCA VALOR NO CONTADOR
		LOOP2_20MS
			DECFSZ	CONTADOR5	; CONTADOR5--
			GOTO LOOP2_20MS
		DECFSZ	CONTADOR4	; CONTADOR4--
		GOTO LOOP1_20MS
	RETURN	; RETORNA
	

;;;;;;;;;; FUNCOES PARA CONTROLAR DISPLAY ;;;;;;;;;;


;APAGAR LEDS
BOTAO_LIB
    BCF	    PORTB, 0   	;Nï¿½O, ACENDE O LED
	BCF	    PORTB, 1   	;Nï¿½O, ACENDE O LED
    BCF	    PORTB, 2  	;Nï¿½O, ACENDE O LED
    BCF	    PORTB, 3  	;Nï¿½O, ACENDE O LED
    BCF	    PORTB, 5  	;Nï¿½O, ACENDE O LED
    BCF	    PORTB, 6  	;Nï¿½O, ACENDE O LED
    BCF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 0
ZERO 	
    BCF     PORTB, 0 ; APAGA O LED
    BSF	    PORTB, 1 ; ACENDE O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BSF	    PORTB, 7 ; ACENDE O LED
	RETURN


;FUNCAO PARA ACENDER DISPLAY NO ANDAR 1
UM 	
    BCF     PORTB, 0 ; APAGA O LED
    BCF     PORTB, 1 ; APAGA O LED
    BCF     PORTB, 2 ; APAGA O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 2
DOIS
    BSF	    PORTB, 0   	; ACENDE O LED
    BCF     PORTB, 1    ; APAGA O LED
	BSF	    PORTB, 2   	; ACENDE O LED 
    BSF	    PORTB, 3   	; ACENDE O LED
    BCF     PORTB, 5    ; APAGA O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 3
TRES
    BSF	    PORTB, 0 ; ACENDE O LED
    BCF     PORTB, 1 ; APAGA O LED
	BSF	    PORTB, 2 ; ACENDE O LED 
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 4
QUATRO
    BSF	    PORTB, 0 ; ACENDE O LED
	BSF	    PORTB, 1 ; ACENDE O LED
    BCF     PORTB, 2 ; APAGA O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 5
CINCO
    BSF	    PORTB, 0 ; ACENDE O LED
	BSF	    PORTB, 1 ; ACENDE O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BCF     PORTB, 3 ; APAGA O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BSF	    PORTB, 6 ; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 6
SEIS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BCF     PORTB, 3 ; APAGA O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 7
SETE
    BCF     PORTB, 0 ; APAGA O LED
    BCF     PORTB, 1 ; APAGA O LED
    BSF	    PORTB, 2 ; ACENDE O LED
    BSF	    PORTB, 3 ; ACENDE O LED
    BSF	    PORTB, 5 ; ACENDE O LED
    BCF     PORTB, 6 ; APAGA O LED
    BCF     PORTB, 7 ; APAGA O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 8
OITO
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 9
NOVE
	BSF	    PORTB, 0   	; ACENDE O LED
    BSF	    PORTB, 1  	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BCF     PORTB, 7 ; APAGA O LED
    RETURN


	END			;OBRIGATï¿½RIO
