#INCLUDE <P16F628A.INC>		;ARQUIVO PADR�O MICROCHIP PARA 16F628A
RADIX DEC
__CONFIG H'3F10'

	CBLOCK	0x20	;ENDERE�O INICIAL DA MEM�RIA DE USU�RIO
	CONTADOR1	
    CONTADOR2
    CONTADOR3
    ATUAL
    AUX
	ENDC			;FIM DO BLOCO DE MEM�RIA		

#DEFINE	BOTAO	PORTA,2	;PORTA DO BOT�O
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

#DEFINE	LED	PORTB,0	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO
	ORG	0x00		;ENDERE�O INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SA�DAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SA�DA
	CLRF	INTCON		;TODAS AS INTERRUP��ES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON		;DEFINE O MODO DO COMPARADOR ANAL�GICO

MAIN
	CALL ZERO      ;DISPLAY 0
    CALL ATRASO 
	CALL UM        ;DISPLAY 1
    CALL ATRASO 
	CALL DOIS      ;DISPLAY 2
    CALL ATRASO
	CALL TRES      ;DISPLAY 3
    CALL ATRASO
	CALL QUATRO    ;DISPLAY 4
    CALL ATRASO
	CALL CINCO     ;DISPLAY 5
    CALL ATRASO
	CALL SEIS      ;DISPLAY 6
    CALL ATRASO
	CALL SETE      ;DISPLAY 7
    CALL ATRASO
    CALL OITO      ;DISPLAY 8
    CALL ATRASO
	CALL NOVE      ;DISPLAY 9
    CALL ATRASO
	CALL OITO      ;DISPLAY 8
    CALL ATRASO
	CALL SETE      ;DISPLAY 7
    CALL ATRASO
	CALL SEIS     ;DISPLAY 6
    CALL ATRASO
	CALL CINCO     ;DISPLAY 5
    CALL ATRASO
	CALL QUATRO    ;DISPLAY 4
    CALL ATRASO
	CALL TRES      ;DISPLAY 3
    CALL ATRASO
	CALL DOIS      ;DISPLAY 2
    CALL ATRASO
	CALL UM        ;DISPLAY 1
    CALL ATRASO
    GOTO MAIN 


;FUNCAO PARA DESCER ELEVADOR CASO O BOTAO FOR PRECIONADO	
INCENDIO



	RETURN

;;;;;;;;;;;;;  FUNCOES DE ATRASO ;;;;;;;;;;;;;
ATRASO				
	MOVLW	105
	MOVWF	CONTADOR1	; contador1=255
    
ATRASO1		
	MOVLW	99
	MOVWF	CONTADOR2	; contador2=40
	NOP
	ATRASO2		
		MOVLW	35
		MOVWF	CONTADOR3	; contador1=129
        BTFSC	BOTAO		;O BOT�O EST� PRESSIONADO?
        GOTO    ATRASO3     ;NAO -> CONTINUAR O LOOP
	    CALL	INCENDIO	;SIM -> IR FUNCAO DE INCENDIO
		ATRASO3	
            NOP	
			NOP
		    DECFSZ	CONTADOR3	; contador3--
			GOTO	ATRASO3     ; se nao for zero continuar loop
	    DECFSZ	CONTADOR2	; contador2--
		GOTO	ATRASO2	; se nao for zero continuar loop
	
    DECFSZ	CONTADOR1	; contador2--
	GOTO	ATRASO1	 ; se nao for zero continuar loop
	RETURN	 ;ir para funcao atraso auxiliar

;FUNCAO PARA ATRASAR 1 MINUTO
ATRASOUMMIM				
	MOVLW	10
	MOVWF	CONTADOR1	; contador1=255
    
ATRASO12		
	MOVLW	99
	MOVWF	CONTADOR2	; contador2=40
	NOP
	ATRASO22		
		MOVLW	35
		MOVWF	CONTADOR3	; contador1=129
        BTFSC	BOTAO		;O BOT�O EST� PRESSIONADO?
        GOTO    ATRASO32     ;NAO -> CONTINUAR O LOOP
	    CALL	INCENDIO	;SIM -> IR FUNCAO DE INCENDIO
		ATRASO32	
            NOP	
			NOP
		    DECFSZ	CONTADOR3	; contador3--
			GOTO	ATRASO32     ; se nao for zero continuar loop
	    DECFSZ	CONTADOR2	; contador2--
		GOTO	ATRASO22	; se nao for zero continuar loop
	
    DECFSZ	CONTADOR1	; contador2--
	GOTO	ATRASO12	 ; se nao for zero continuar loop
	RETURN	 ;ir para funcao atraso auxiliar


;;;;;;;;;; FUNCOES PARA CONTROLAR DISPLAY ;;;;;;;;;;


;APAGAR LEDS
BOTAO_LIB
    BCF	    PORTB, 0   	;N�O, ACENDE O LED
	BCF	    PORTB, 1   	;N�O, ACENDE O LED
    BCF	    PORTB, 2  	;N�O, ACENDE O LED
    BCF	    PORTB, 3  	;N�O, ACENDE O LED
    BCF	    PORTB, 5  	;N�O, ACENDE O LED
    BCF	    PORTB, 6  	;N�O, ACENDE O LED
    BCF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 0
ZERO 	
    MOVLW	0
	MOVWF	ATUAL	; ATUAL = 0
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2   	; ACENDE O LED
    BSF	    PORTB, 3   	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6   	; ACENDE O LED
    BSF	    PORTB, 7   	; ACENDE O LED
	RETURN


;FUNCAO PARA ACENDER DISPLAY NO ANDAR 1
UM 	
    MOVLW	1
	MOVWF	ATUAL	; ATUAL = 1
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 3   	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 2
DOIS
    MOVLW	2
	MOVWF	ATUAL	; ATUAL = 2
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 2   	; ACENDE O LED 
    BSF	    PORTB, 3   	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 3
TRES
    MOVLW	3
	MOVWF	ATUAL	; ATUAL = 3
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 2   	; ACENDE O LED 
    BSF	    PORTB, 3   	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 4
QUATRO
    MOVLW	4
	MOVWF	ATUAL	; ATUAL = 4
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 5
CINCO
    MOVLW	5
	MOVWF	ATUAL	; ATUAL = 5
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 6
SEIS
    MOVLW	6
	MOVWF	ATUAL	; ATUAL = 6
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 7
SETE
    MOVLW	7
	MOVWF	ATUAL	; ATUAL = 7
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 8
OITO
    MOVLW	8
	MOVWF	ATUAL	; ATUAL = 8
    CALL BOTAO_LIB ;APAGAR LEDS
    BSF	    PORTB, 0   	; ACENDE O LED
	BSF	    PORTB, 1   	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    BSF	    PORTB, 7  	; ACENDE O LED
	RETURN

;FUNCAO PARA ACENDER DISPLAY NO ANDAR 9
NOVE
    MOVLW	9
	MOVWF	ATUAL	; ATUAL = 9
    CALL BOTAO_LIB ;APAGAR LEDS
	BSF	    PORTB, 0   	; ACENDE O LED
    BSF	    PORTB, 1  	; ACENDE O LED
    BSF	    PORTB, 2  	; ACENDE O LED
    BSF	    PORTB, 3  	; ACENDE O LED
    BSF	    PORTB, 5  	; ACENDE O LED
    BSF	    PORTB, 6  	; ACENDE O LED
    RETURN


	END			;OBRIGAT�RIO


